<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.secretsoft</groupId>
	<artifactId>ground-taxi-network-tool</artifactId>
	<version>1.0.0-SNAPSHOT</version>

	<properties>
		<java.version>21</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<!-- Spring -->
		<spring-boot-starter.version>4.0.4</spring-boot-starter.version>

		<!-- Vaadin -->
		<vaadin.version>25.0.7</vaadin.version>

		<!-- Apache -->
		<commons-lang3.version>3.20.0</commons-lang3.version>

		<!-- JAXB -->
		<jakarta.activation-api.version>2.1.3</jakarta.activation-api.version>
		<jaxb-core.version>4.0.5</jaxb-core.version>
		<jakarta.xml.bind-api.version>4.0.2</jakarta.xml.bind-api.version>
		<jaxb-runtime.verion>4.0.5</jaxb-runtime.verion>
		<jaxb-xjc.verion>4.0.5</jaxb-xjc.verion>
		<threeten-jaxb-core.version>2.2.0</threeten-jaxb-core.version>

		<!-- XStream -->
		<xstream.version>1.4.20</xstream.version>

		<!-- Lombok -->
		<lombok.version>1.18.44</lombok.version>

		<!-- Plugins -->
		<jaxb2-maven-plugin.version>3.1.0</jaxb2-maven-plugin.version>

		<!-- Test -->
		<junit-pioneer.version>2.2.0</junit-pioneer.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!-- Spring -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot-starter.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- Vaadin -->
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- Apache -->
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-lang3.version}</version>
			</dependency>

			<!-- JAXB -->
			<dependency>
				<groupId>jakarta.xml.bind</groupId>
				<artifactId>jakarta.xml.bind-api</artifactId>
				<version>${jakarta.xml.bind-api.version}</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
				<version>${jaxb-runtime.verion}</version>
			</dependency>
			<dependency>
				<groupId>io.github.threeten-jaxb</groupId>
				<artifactId>threeten-jaxb-core</artifactId>
				<version>${threeten-jaxb-core.version}</version>
			</dependency>

			<!-- XStream -->
			<dependency>
				<groupId>com.thoughtworks.xstream</groupId>
				<artifactId>xstream</artifactId>
				<version>${xstream.version}</version>
			</dependency>

			<!-- Lombok -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>

			<!-- Test -->
			<dependency>
				<groupId>org.junit-pioneer</groupId>
				<artifactId>junit-pioneer</artifactId>
				<version>${junit-pioneer.version}</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Spring -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Vaadin -->
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-dev</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
		</dependency>

		<!-- Apache -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<!-- Jackson -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>

		<!-- JAXB -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-oxm</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.threeten-jaxb</groupId>
			<artifactId>threeten-jaxb-core</artifactId>
		</dependency>

		<!-- XStream -->
		<dependency>
			<groupId>com.thoughtworks.xstream</groupId>
			<artifactId>xstream</artifactId>
		</dependency>

		<!-- Database -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit-pioneer</groupId>
			<artifactId>junit-pioneer</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>ground-taxi-network-tool</finalName>
		<plugins>
			<!-- Spring -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot-starter.version}</version>
				<configuration>
					<layout>ZIP</layout>
					<wait>500</wait>
					<maxAttempts>240</maxAttempts>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>build-info</goal>
						</goals>
					</execution>
					<execution>
						<id>spring-boot-repackage-app</id>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<classifier>app</classifier>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Vaadin -->
			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-frontend</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- JAXB -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<version>${jaxb2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>kml21</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/xsd/kml.xsd</source>
							</sources>
							<xjbSources>
								<xjbSource>src/main/xjb/kml.xjb</xjbSource>
							</xjbSources>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>jakarta.activation</groupId>
						<artifactId>jakarta.activation-api</artifactId>
						<version>${jakarta.activation-api.version}</version>
					</dependency>
					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-runtime</artifactId>
						<version>${jaxb-runtime.verion}</version>
					</dependency>
					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-core</artifactId>
						<version>${jaxb-core.version}</version>
					</dependency>
					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-xjc</artifactId>
						<version>${jaxb-xjc.verion}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<!-- Production mode is activated using -Pproduction -->
			<id>production</id>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>com.vaadin</groupId>
							<artifactId>vaadin-maven-plugin</artifactId>
							<version>${vaadin.version}</version>
							<executions>
								<execution>
									<goals>
										<goal>build-frontend</goal>
									</goals>
									<phase>compile</phase>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
	</profiles>
</project>
